name: Build and Push Site

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Deploy Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7.x'
      - name: Deploy Site
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # CUSTOM_DOMAIN: toolchanger.xyz
